services:

  postgres:
    image: postgres:14-alpine
    ports:
      - 1234:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=ExpenseTracker

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=sa
      - RABBITMQ_DEFAULT_PASS=a.A12345